### ISSUE TITLE
Cannot find module 'styled-jsx/style'

### ISSUE THREAD

**Issue by leebenson** [graphcool/graphql-playground#157]
With 1.0.4:

> Error: Cannot find module 'styled-jsx/style'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphql-playground/lib/components/Playground.js:5:14)
    at Module._compile (module.js:573:30)

**Comment by oliverjam** [comment]
Yeah I got the same issue trying to use this with Create React App. I manually installed styled-jsx, and now it's complaining that there's no Redux store. Are we somehow running an unbundled/not-production version of Playground?

**Comment by leebenson** [comment]
Very possibly @oliverjam. I'm trying to get it working with [ReactQL](https://github.com/reactql/kit), and it could be the Webpack config I'm using locally which is interfering somehow. I'll go ahead and close this for now, since I don't have any specifics.

**Comment by jasonbahl** [comment]
I get the same with Create React App. 

> Error: Cannot find module 'styled-jsx/style'

Then when I add `styled-jsx` as a dep in my package.json, that goes away but I get:

>Uncaught Error: Could not find "store" in either the context or props of "Connect(Playground)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Playground)"

**Comment by mstuart** [comment]
+1 Hmm, same here.  node8, just `npm install graphql-playground --save`, then followed the Express directions.

Got:
```
Error: Cannot find module 'styled-jsx/style'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (~/node_modules/graphql-playground/lib/components/Playground.js:5:14)
```

Then `npm install style-jsx --save`.

Now:
```
ReferenceError: self is not defined
    at Object.hasOwnProperty (~/node_modules/graphcool-styles/dist/build.js:325:18)
    at __webpack_require__ (~/node_modules/graphcool-styles/dist/build.js:30:30)
    at Object.exports.black (~/node_modules/graphcool-styles/dist/build.js:98:1)
    at __webpack_require__ (~/node_modules/graphcool-styles/dist/build.js:30:30)
    at Object.<anonymous> (~/node_modules/graphcool-styles/dist/build.js:894:14)
    at __webpack_require__ (~/node_modules/graphcool-styles/dist/build.js:30:30)
    at ~/node_modules/graphcool-styles/dist/build.js:74:18
    at ~/node_modules/graphcool-styles/dist/build.js:77:10
    at webpackUniversalModuleDefinition (~/node_modules/graphcool-styles/dist/build.js:3:20)
```

**Comment by mstuart** [comment]
@leebenson how are you integrating it in?  Express middleware?

**Comment by leebenson** [comment]
@mstuart - I was attempting to integrate via the Koa middleware

**Comment by leebenson** [comment]
I've reopened the issue since it seems to be affecting a few users

**Comment by SaraVieira** [comment]
I still get this problem and I using it as react component @timsuchanek 

```
import React from 'react'
import Playground from 'graphql-playground'
import 'graphql-playground/playground.css'

const Home = () => (
  <Playground endpoint='/graphql' />
)

export default Home
```

```
/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:325
module.exports = self.fetch.bind(self);
                 ^

ReferenceError: self is not defined
    at Object.hasOwnProperty (/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:325:18)
    at __webpack_require__ (/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:30:30)
    at Object.exports.black (/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:98:1)
    at __webpack_require__ (/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:30:30)
    at Object.<anonymous> (/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:894:14)
    at __webpack_require__ (/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:30:30)
    at /Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:74:18
    at /Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:77:10
    at webpackUniversalModuleDefinition (/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:3:20)
    at Object.<anonymous> (/Users/flyingunicornaway/Projects/graphql-portfolio/node_modules/graphcool-styles/dist/build.js:10:3)
```

**Comment by morajabi** [comment]
@SaraVieira It's a problem with the build, we'll migrate to styled-components from styled-jsx but until then I think Tim can take a look at the build config.
