### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by leebenson** [graphcool/graphql-playground#158]
From 1.0.4:

> /Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:325
module.exports = self.fetch.bind(self);
                 ^
> ReferenceError: self is not defined
    at Object.hasOwnProperty (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:325:18)
    at __webpack_require__ (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:30:30)
    at Object.exports.black (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:98:1)
    at __webpack_require__ (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:30:30)
    at Object.<anonymous> (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:894:14)
    at __webpack_require__ (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:30:30)
    at /Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:74:18
    at /Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:77:10
    at webpackUniversalModuleDefinition (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:3:20)
    at Object.<anonymous> (/Users/leebenson/dev/sandbox/reactql-485/node_modules/graphcool-styles/dist/build.js:10:3)

**Comment by morajabi** [comment]
It's not clear what exactly is the issue. @leebenson Can you provide more info if it's not solved yet?

**Comment by mstuart** [comment]
Was able to repro this by following these steps -- https://github.com/graphcool/graphql-playground/issues/157#issuecomment-339869869

**Comment by leebenson** [comment]
@mstuart - the two issues definitely seem related -- I encountered both this as #157 in the same session
