### ISSUE TITLE
Runtime error when using npm install --only=production

### ISSUE THREAD

**Issue by lightsprint09** [graphcool/graphql-playground#221]
#### This issue pertains to:

- [ ] GraphQL Playground - Electron App
- [x] GraphQL Playground

#### What OS and OS version are you experiencing the issue(s) on?
Mac OS X
npm 4.6.1

#### What version of graphql-playground(-electron) are you experience the issue(s) on?
playground: 1.1.1

#### What is the expected behavior?
No runtime crash

#### What is the actual behavior?
```
Error: Cannot find module 'graphql-playground/middleware'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lukaslaschmidt/Developer/hackberlin/index.js:5:27)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

#### What steps may we take to reproduce the behavior?
```
npm install --only=production

npm start
```

**Comment by lightsprint09** [comment]
I missed explicit express middleware dependencie

**Comment by kbrandwijk** [comment]
In that version, the middleware was moved to a separate package. You shouldn't install `graphql-playground`, but _only_ `graphql-playground-middleware`.
