### ISSUE TITLE
Please check if the endpoint 'undefined' is a valid GraphQL Endpoint.

### ISSUE THREAD

**Issue by DaleJefferson** [graphcool/graphql-playground#287]
#### This issue pertains to:

- [x] graphql-playground-middleware-lambda

#### What OS and OS version are you experiencing the issue(s) on?

Mac OS, Chrome 63, AWS Lambda Node 6.10

#### What version of graphql-playground(-electron/-middleware) are you experience the issue(s) on?

1.3.1

#### What is the expected behavior?

Successfully load the playground

#### What is the actual behavior?

I see an error message

> Schema could not be fetched. Please check if the endpoint 'undefined' is a valid GraphQL Endpoint.

Strangly queries work so it's just the schema fetching that is broken.

```
POST http://localhost:3000/undefined 404 (Not Found)

DOMException: Failed to construct 'WebSocket': The URL 'graphql' is invalid.
    at e.connect (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:1381884)
    at new e (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:1375721)
    at n.o.setWS (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:971800)
    at n.resetSubscription (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:986023)
    at https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:985841
    at Array.forEach (<anonymous>)
    at n.resetSubscriptions (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:985812)
    at n.<anonymous> (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:981685)
    at commitCallbacks (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:833667)
    at commitLifeCycles (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:786909)
    at n (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:790837)
    at u (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:792504)
    at l (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:792947)
    at h (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:794970)
    at f (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:794479)
    at Object.enqueueSetState (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:775731)
    at t.i.setState (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:755421)
    at t.<anonymous> (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:969046)
    at r (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:961593)
    at Object.next (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:960928)
    at a (https://cdn.jsdelivr.net/npm/graphql-playground@1.3.1/build/static/js/middleware.js:1:960694)
    at <anonymous>
o.setWS @ Playground.tsx:268
n.resetSubscription @ Playground.tsx:676
(anonymous) @ Playground.tsx:667
n.resetSubscriptions @ Playground.tsx:667
(anonymous) @ Playground.tsx:226
commitCallbacks @ react-dom.production.min.js:109
commitLifeCycles @ react-dom.production.min.js:169
n @ react-dom.production.min.js:180
u @ react-dom.production.min.js:183
l @ react-dom.production.min.js:184
h @ react-dom.production.min.js:188
f @ react-dom.production.min.js:187
enqueueSetState @ react-dom.production.min.js:140
i.setState @ react.production.min.js:12
(anonymous) @ MiddlewareApp.tsx:458
r @ middleware.js:66538
(anonymous) @ middleware.js:66504
a @ middleware.js:66471
Promise resolved (async)
c @ middleware.js:66486
(anonymous) @ middleware.js:66488
c @ middleware.js:66468
t.updateSubscriptionsUrl @ middleware.js:66854
t.componentDidMount @ MiddlewareApp.tsx:240
commitLifeCycles @ react-dom.production.min.js:169
n @ react-dom.production.min.js:180
u @ react-dom.production.min.js:183
l @ react-dom.production.min.js:184
h @ react-dom.production.min.js:188
f @ react-dom.production.min.js:187
updateContainer @ react-dom.production.min.js:248
(anonymous) @ react-dom.production.min.js:254
unbatchedUpdates @ react-dom.production.min.js:190
dt @ react-dom.production.min.js:254
render @ react-dom.production.min.js:255
init @ middlewareIndex.tsx:18
(anonymous) @ playground:48
```

#### What steps may we take to reproduce the behavior?

Upgrade to graphql-playground-middleware-lambda 1.3.1

```js
import lambdaPlayground from 'graphql-playground-middleware-lambda'

export const handler = lambdaPlayground({endpoint: 'graphql'})
```

![screen shot 2017-12-01 at 13 55 17](https://user-images.githubusercontent.com/375005/33485925-17408d7e-d6a0-11e7-947f-f42610de4fb7.png)

**Comment by timsuchanek** [comment]
@DaleJefferson I think the problem is, that you're providing `graphql` as the endpoint. But it should rather be `/graphql`or `/dev/graphql` if your stage in serverless/lambda is `dev`.
I created an example here:
https://github.com/graphcool/graphql-playground/tree/master/packages/graphql-playground-middleware-lambda/examples/basic

It's deployed here: https://1rp2h4rth8.execute-api.us-east-1.amazonaws.com/dev/playground

Does that solve your issue?

The issue for the `graphql-playground` here is definitely to provide better error handling.
I create a separate issue for that.

**Comment by JstnEdr** [comment]
I'm experiencing the same problem. While I haven't yet found a fix, I have found a workaround that hopefully helps diagnose the root problem. For me, using the default `/graphql` path results in this error.

> Schema could not be fetched. Please check if the endpoint 'undefined' is a valid GraphQL Endpoint.

But if I change the http path in `/app-backend/serverless.yml` to `graphqltest` and also change the `REACT_APP_GRAPHQL_ENDPOINT` in `/config/security.env.local` to `/graphqltest`, I then get a working Playground. I know this isn't a full fix, but it may be a clue as to where the problem is stemming from.

**Comment by DaleJefferson** [comment]
I've just upgraded to `"graphql-playground-middleware-lambda": "1.3.6"` and everything seems to be working now. Thanks for the prompt response. 🥇
